version: "3.5"

services:
  db:
    image: postgres
    restart: always
    environment:
      - POSTGRES_USER=user
      - POSTGRES_PASSWORD=12345678
      - POSTGRES_DB=upload-archive
    container_name: upload-archive
    volumes:
      - ./pgdata:/var/lib/postgresql/data
    ports:
      - "5432:5432"

volumes:
  db:
